var searchData=
[
  ['readme_2emd',['readme.md',['../readme_8md.html',1,'(Global Namespace)'],['../readme_8md.html',1,'(Global Namespace)']]],
  ['reinit',['reinit',['../class_residual.html#a683e96e9d88d46820c0964786424fdf2',1,'Residual']]],
  ['reinitlinearsystem',['reinitLinearSystem',['../classsolve_class.html#ab8aad4ce80f4f6fe8532c53e4bba67ec',1,'solveClass']]],
  ['reinitmethod',['reinitMethod',['../classsolve_class.html#a586d70f40869aa09462cc19291702910',1,'solveClass']]],
  ['reinitparams',['reinitParams',['../classsolve_class.html#aa4ad1317ebf556afc0f3ffeed490dbb4',1,'solveClass']]],
  ['residual',['Residual',['../class_residual.html',1,'Residual&lt; T, dim &gt;'],['../class_residual.html#a4b540ba8e3ad0a1f8cfe2b4acd20493b',1,'Residual::Residual()']]],
  ['residual_2ecc',['residual.cc',['../residual_8cc.html',1,'']]],
  ['residual_2eh',['Residual.h',['../_residual_8h.html',1,'']]],
  ['residualforconstanteq',['residualForConstantEq',['../class_residual.html#ab1fcf2c2ae911f4d0c73e59e60f1e6ad',1,'Residual::residualForConstantEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 1, T &gt; &amp;value)'],['../class_residual.html#a5d0f09e08ac7a6603bab9f192fd3c109',1,'Residual::residualForConstantEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 2, T &gt; &amp;value)']]],
  ['residualforcontinuityeq',['residualForContinuityEq',['../class_residual.html#a882f4595a6547599cfe8f65897f45896',1,'Residual::residualForContinuityEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, Table&lt; 1, T &gt; &amp;R, Table&lt; 1, T &gt; &amp;divVelocity)'],['../class_residual.html#afddbdda003424f242266894fdd1f7b1a',1,'Residual::residualForContinuityEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, Table&lt; 1, T &gt; &amp;R, deformationMap&lt; T, dim &gt; &amp;defMap, Table&lt; 1, T &gt; &amp;divVelocity)']]],
  ['residualfordiff_5freaceq',['residualForDiff_ReacEq',['../class_residual.html#a144663fb81fc60d4db0c5a8e45176e61',1,'Residual::residualForDiff_ReacEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 1, T &gt; &amp;c, dealii::Table&lt; 1, double &gt; &amp;c_conv, dealii::Table&lt; 2, T &gt; &amp;flux, dealii::Table&lt; 1, T &gt; &amp;reaction)'],['../class_residual.html#aa88dcdddfeefb2ba5f1f1196d8608b70',1,'Residual::residualForDiff_ReacEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, deformationMap&lt; T, dim &gt; &amp;defMap, dealii::Table&lt; 1, T &gt; &amp;c, dealii::Table&lt; 1, double &gt; &amp;c_conv, dealii::Table&lt; 2, T &gt; &amp;flux, dealii::Table&lt; 1, T &gt; &amp;reaction)']]],
  ['residualfordiffusioneq',['residualForDiffusionEq',['../class_residual.html#a224462af849f5a1927bc90eb3795f2f2',1,'Residual::residualForDiffusionEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 1, T &gt; &amp;c, dealii::Table&lt; 1, double &gt; &amp;c_conv, dealii::Table&lt; 2, T &gt; &amp;flux)'],['../class_residual.html#a69b8ab1cc85ae177f9c627b60b1b8468',1,'Residual::residualForDiffusionEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, deformationMap&lt; T, dim &gt; &amp;defMap, dealii::Table&lt; 1, T &gt; &amp;c, dealii::Table&lt; 1, double &gt; &amp;c_conv, dealii::Table&lt; 2, T &gt; &amp;flux)']]],
  ['residualforgeneralweakform',['residualForGeneralWeakForm',['../class_residual.html#ab90bb5476a96c0e7098264562b313b7b',1,'Residual::residualForGeneralWeakForm(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 1, T &gt; &amp;scalar_term, dealii::Table&lt; 2, T &gt; &amp;vector_term)'],['../class_residual.html#a478a5fee7d75f3a16707ad5915a34d3f',1,'Residual::residualForGeneralWeakForm(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, deformationMap&lt; T, dim &gt; &amp;defMap, dealii::Table&lt; 1, T &gt; &amp;scalar_term, dealii::Table&lt; 2, T &gt; &amp;vector_term)']]],
  ['residualformechanics',['residualForMechanics',['../class_residual.html#a432fe02216f182fd241f09775131f854',1,'Residual']]],
  ['residualfornavier_5fstokeseq',['residualForNavier_StokesEq',['../class_residual.html#a34f1f680e957e21ac47c35f404e9fd6a',1,'Residual']]],
  ['residualforneummanbc',['residualForNeummanBC',['../class_residual.html#a4c8fd158c8034b25780abfe785755baa',1,'Residual::residualForNeummanBC(const FEValues&lt; dim &gt; &amp;fe_values, const FEFaceValues&lt; dim &gt; &amp;fe_face_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 2, T &gt; &amp;gradn)'],['../class_residual.html#ad0e81fca1fe14909b80e709c1e93e393',1,'Residual::residualForNeummanBC(const FEValues&lt; dim &gt; &amp;fe_values, const FEFaceValues&lt; dim &gt; &amp;fe_face_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 1, T &gt; &amp;gradn)'],['../class_residual.html#af2aedfc68848cd35cac392aad840db05',1,'Residual::residualForNeummanBC(const FEValues&lt; dim &gt; &amp;fe_values, const FEFaceValues&lt; dim &gt; &amp;fe_face_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, deformationMap&lt; T, dim &gt; &amp;defMap, dealii::Table&lt; 1, T &gt; &amp;gradn)'],['../class_residual.html#a1e66cf9fc807561fc00cffb93c52d37d',1,'Residual::residualForNeummanBC(const FEValues&lt; dim &gt; &amp;fe_values, const FEFaceValues&lt; dim &gt; &amp;fe_face_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, double gradn)']]],
  ['residualforpoissoneq',['residualForPoissonEq',['../class_residual.html#af1d58eecf6eeae74de2f7ebc6a158b18',1,'Residual::residualForPoissonEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 2, T &gt; &amp;phi_grad, dealii::Table&lt; 1, T &gt; &amp;rhs)'],['../class_residual.html#ad457db9bcfe7ff4d134642440cd1c4e6',1,'Residual::residualForPoissonEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, deformationMap&lt; T, dim &gt; &amp;defMap, dealii::Table&lt; 2, T &gt; &amp;phi_grad, dealii::Table&lt; 1, T &gt; &amp;rhs)'],['../class_residual.html#ad1d5fc375c6f93d9aad89fc1cf9fd25f',1,'Residual::residualForPoissonEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, dealii::Table&lt; 3, T &gt; &amp;phi_grad, dealii::Table&lt; 2, T &gt; &amp;rhs)'],['../class_residual.html#ada0899a86c88ceb84cc3c1155663b8ba',1,'Residual::residualForPoissonEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, dealii::Table&lt; 1, T &gt; &amp;R, deformationMap&lt; T, dim &gt; &amp;defMap, dealii::Table&lt; 3, T &gt; &amp;phi_grad, dealii::Table&lt; 2, T &gt; &amp;rhs)']]],
  ['residualforstokeseq',['residualForStokesEq',['../class_residual.html#a9a8f493fb66e0bd394948af13a27d821',1,'Residual::residualForStokesEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, Table&lt; 1, T &gt; &amp;R, Table&lt; 3, T &gt; &amp;gradV, dealii::Table&lt; 1, T &gt; &amp;pressure)'],['../class_residual.html#a95ad863ab9066d2dbfef9db3907a911f',1,'Residual::residualForStokesEq(const FEValues&lt; dim &gt; &amp;fe_values, unsigned int DOF, Table&lt; 1, T &gt; &amp;R, deformationMap&lt; T, dim &gt; &amp;defMap, Table&lt; 3, T &gt; &amp;gradV, dealii::Table&lt; 1, T &gt; &amp;pressure)']]],
  ['resume_5fvector_5ffrom_5fsnapshot',['resume_vector_from_snapshot',['../class_f_e_mdata.html#a2611613e158345b619062316e281c4c9',1,'FEMdata']]]
];
